name: $(date:yyyy.MM.dd)$(rev:.r)
trigger:
  batch: true
  branches:
    include:
      - main

stages:
  - stage: Build
    displayName: Build function app
    jobs:
      - job: Build
        displayName: Build app
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
            clean: true

          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              mavenOptions: '-Xmx3072m'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.11'
              jdkArchitectureOption: 'x64'
              goals: 'clean package'

          - task: CopyFiles@2
            displayName: 'Copy function package to artifacts'
            inputs:
              SourceFolder: $(system.defaultworkingdirectory)/target/azure-functions/sensor-app/
              Contents: '**'
              TargetFolder: $(build.artifactstagingdirectory)/package/

          - task: CopyFiles@2
            displayName: 'Copy resource template to artifacts'
            inputs:
              SourceFolder: infrastructure/templates
              Contents: resourceGroup.iac.json
              TargetFolder: '$(build.artifactstagingdirectory)'

          - publish: $(build.artifactstagingdirectory)
            displayName: 'Publish Artifact: drop'
            artifact: drop
            condition: succeededOrFailed()

  - stage: Deploy
    displayName: Deploy function app
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
      - deployment: Deploy
        pool:
          vmImage: 'ubuntu-latest'
        environment: 'Production'
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: drop

                - task: AzureResourceManagerTemplateDeployment@3
                  displayName: Deploy resource group infrastructure
                  inputs:
                    deploymentScope: 'Resource Group'
                    azureResourceManagerConnection: $(azureResourceManagerConnection)
                    subscriptionId: $(subscriptionId)
                    action: 'Create Or Update Resource Group'
                    resourceGroupName: $(resourceGroupName)
                    location: $(location)
                    templateLocation: 'Linked artifact'
                    csmFile: '$(Pipeline.Workspace)/drop/resourceGroup.iac.json'
                    deploymentMode: 'Incremental'
                    deploymentName: 'continuous-deployment'

                - task: AzureFunctionApp@1
                  displayName: Deploy function app
                  inputs:
                    azureSubscription: $(azureResourceManagerConnection)
                    appType: 'functionAppLinux'
                    appName: $(appName)
                    package: '$(Pipeline.Workspace)/drop/package'
                    appSettings: '-FUNCTIONS_EXTENSION_VERSION ~3'
                    runtimeStack: 'DOCKER|mcr.microsoft.com/azure-functions/java:3.0-java11-appservice'
